/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '//second'
    >,
    '//second': RouteRecordInfo<
      '//second',
      '/second',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/admin': RouteRecordInfo<
      '/admin',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | '/admin/'
      | '/admin/datos-local'
      | '/admin/datosFuncionario'
      | '/admin/horarios'
    >,
    '/admin/': RouteRecordInfo<
      '/admin/',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/datos-local': RouteRecordInfo<
      '/admin/datos-local',
      '/admin/datos-local',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/datosFuncionario': RouteRecordInfo<
      '/admin/datosFuncionario',
      '/admin/datosFuncionario',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/horarios': RouteRecordInfo<
      '/admin/horarios',
      '/admin/horarios',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/funcionario': RouteRecordInfo<
      '/funcionario',
      '/funcionario',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/misturnos': RouteRecordInfo<
      '/misturnos',
      '/misturnos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/pantalla-tv': RouteRecordInfo<
      '/pantalla-tv',
      '/pantalla-tv',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/registro': RouteRecordInfo<
      '/registro',
      '/registro',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sacar-turno': RouteRecordInfo<
      '/sacar-turno',
      '/sacar-turno',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/totem': RouteRecordInfo<
      '/totem',
      '/totem',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
        | '//second'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/index/second.vue': {
      routes:
        | '//second'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/admin.vue': {
      routes:
        | '/admin'
        | '/admin/'
        | '/admin/datos-local'
        | '/admin/datosFuncionario'
        | '/admin/horarios'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/admin/index.vue': {
      routes:
        | '/admin/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/datos-local.vue': {
      routes:
        | '/admin/datos-local'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/datosFuncionario.vue': {
      routes:
        | '/admin/datosFuncionario'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/horarios.vue': {
      routes:
        | '/admin/horarios'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/funcionario.vue': {
      routes:
        | '/funcionario'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/misturnos.vue': {
      routes:
        | '/misturnos'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/pantalla-tv.vue': {
      routes:
        | '/pantalla-tv'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/registro.vue': {
      routes:
        | '/registro'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/sacar-turno.vue': {
      routes:
        | '/sacar-turno'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/totem.vue': {
      routes:
        | '/totem'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
